title: react-firebase-state
description: Documentation for the react-firebase-state component library
theme: just-the-docs

url: https://gmcfall.github.io/react-firebase-state-docs

aux_links:
  Github Repository: https://gmcfall.github.io/react-firebase-state-docs

callouts:
  highlight:
    color: yellow
  prerequisites:
    title: Prerequisites
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

